name: venvexploration
channels:
  - conda-forge
  - defaults
  - pytorch
  - plotly
dependencies:
  - defaults::python=3.10.9
  - conda-forge::cudatoolkit=11.3
  - pytorch::pytorch=1.12.1
  - defaults::scikit-learn=1.2.2
  - defaults::pandas=1.5.3
  - defaults::matplotlib=3.7.0
  - defaults::jupyter=1.0.0
  - defaults::tqdm=4.65.0
  - plotly::plotly=5.18.0
  - conda-forge::wandb=0.15.12